# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-backend-lklv"
    dynamodb_table = "terraform-up-and-running-locks"
    encrypt        = true
    key            = "environments/dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
